### ISSUE TITLE
Crash on app opening on Samsung A32

### ISSUE THREAD

**Issue by f0enix** [mirsadm/motioncam#43]
The app v7.0.5 crashes instantly on my Samsung A32 running Android 11.0. The phone has multiple cameras but it seems the app failed to get the details about certain cameras and hence crashed. 

**E/ACameraManager: Get camera characteristics from camera service failed: Status(-8, EX_SERVICE_SPECIFIC): '10: getCameraCharacteristics:911: Unable to retrieve cameracharacteristics for system only device 3: '**

This seems to be the same exact issue as [https://github.com/mirsadm/motioncam/issues/30](https://github.com/mirsadm/motioncam/issues/30) which is happening on Meizu 16X Android 8.1. 
Can you provide a patch for it?

Here is the full log:
```
2021-12-08 12:13:11.627 1320-1320/? E/Native_CFMS: nativePerfMgrRemoveTask    Fail    tid : -1    return : -1
2021-12-08 12:13:11.704 1320-1559/? E/WifiVendorHal: getWifiLinkLayerStats_1_3_Internal(l.974) failed {.code = ERROR_NOT_SUPPORTED, .description = }
2021-12-08 12:13:11.758 1720-1720/? E/ExpandableNotifRow: onNotificationUpdated() NSSL is null..
2021-12-08 12:13:11.861 1320-1320/? E/Native_CFMS: nativePerfMgrRemoveTask    Fail    tid : -1    return : -1
2021-12-08 12:13:12.394 2728-10930/? E/pageboostd: alp start : app commotioncam
2021-12-08 12:13:12.394 1320-1670/? E/ActivityTaskManager: TouchDown intent received, starting ActiveLaunch
2021-12-08 12:13:12.396 2728-10930/? E/pageboostd: commotioncam, amt 12863940 scnt 2 fcnt 0
2021-12-08 12:13:12.397 2728-10930/? E/pageboostd: commotioncam, amt 0 scnt 2 fcnt 0
2021-12-08 12:13:12.397 2728-10930/? E/pageboostd: alp end : app commotioncam data_amount 12863940
2021-12-08 12:13:12.426 6506-6506/? E/com.motioncam: Not starting debugger since process cannot load the jdwp agent.
2021-12-08 12:13:12.444 2728-2728/? E/pageboostd: Received HALT command code 2
2021-12-08 12:13:12.490 2728-2728/? E/pageboostd: Received HALT command code 2
2021-12-08 12:13:12.512 1320-1634/? E/PkgPredictorService-Collector: record changed bt=1  wifi=1 screen=0
2021-12-08 12:13:12.547 1320-1320/? E/Native_CFMS: nativePerfMgrRemoveTask    Fail    tid : -1    return : -1
2021-12-08 12:13:12.776 844-992/? E/connsyslogger: Bootup Log: 0 log files! 
2021-12-08 12:13:12.787 6506-6506/? E/ACameraManager: Get camera characteristics from camera service failed: Status(-8, EX_SERVICE_SPECIFIC): '10: getCameraCharacteristics:911: Unable to retrieve cameracharacteristics for system only device 3: '
2021-12-08 12:13:12.787 843-1768/? E/CameraService: shouldRejectSystemCameraConnection: Invalid camera id 4, 
2021-12-08 12:13:12.787 6506-6506/? E/ACameraManager: Get camera characteristics from camera service failed: Status(-8, EX_SERVICE_SPECIFIC): '10: getCameraCharacteristics:911: Unable to retrieve cameracharacteristics for system only device 4: '
2021-12-08 12:13:12.812 754-754/? E/Layer: [Surface(name=Task=1)/@0x351974c - animation-leash#0] No local sync point found
2021-12-08 12:13:12.812 754-754/? E/Layer: [Surface(name=Task=31)/@0x6662484 - animation-leash#0] No local sync point found
2021-12-08 12:13:12.840 6506-6506/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.motioncam, PID: 6506
    java.lang.RuntimeException: Unable to resume activity {com.motioncam/com.motioncam.CameraActivity}: java.lang.NullPointerException: Attempt to read from field 'java.lang.String com.motioncam.camera.NativeCameraInfo.cameraId' on a null object reference
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4907)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4944)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2325)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8633)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
     Caused by: java.lang.NullPointerException: Attempt to read from field 'java.lang.String com.motioncam.camera.NativeCameraInfo.cameraId' on a null object reference
        at com.motioncam.camera.NativeCameraSessionBridge.getMetadata(NativeCameraSessionBridge.java:359)
        at com.motioncam.CameraActivity.initCamera(CameraActivity.java:1647)
        at com.motioncam.CameraActivity.onResume(CameraActivity.java:542)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1456)
        at android.app.Activity.performResume(Activity.java:8353)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4897)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4944) 
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2325) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:246) 
        at android.app.ActivityThread.main(ActivityThread.java:8633) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130) 
2021-12-08 12:13:12.864 1320-3094/? E/WindowManager: win=Window{ae1f24e u0 com.sec.android.app.launcher/com.sec.android.app.launcher.activities.LauncherActivity} destroySurfaces: appStopped=false win.mWindowRemovalAllowed=false win.mRemoveOnExit=false win.mViewVisibility=8 caller=com.android.server.wm.ActivityRecord.destroySurfaces:5251 com.android.server.wm.ActivityRecord.notifyAppResumed:5272 com.android.server.wm.ActivityStack.resumeTopActivityInnerLocked:2386 com.android.server.wm.ActivityStack.resumeTopActivityUncheckedLocked:1873 com.android.server.wm.ActivityRecord.makeActiveIfNeeded:5510 com.android.server.wm.ActivityRecord.makeVisibleIfNeeded:5414 com.android.server.wm.EnsureActivitiesVisibleHelper.setActivityVisibilityState:187 
2021-12-08 12:13:12.890 3164-3188/? E/TaskStackListenerAbstract: onTaskSnapshotChanged called by Binder.getCallingPid() 0 android.app.ITaskStackListener$Stub.onTransact:587 android.os.Binder.execTransactInternal:1195 android.os.Binder.execTransact:1159 <bottom of call stack> 
2021-12-08 12:13:12.890 1720-2415/? E/TaskStackListenerAbstract: onTaskSnapshotChanged called by Binder.getCallingPid() 0 android.app.ITaskStackListener$Stub.onTransact:587 android.os.Binder.execTransactInternal:1195 android.os.Binder.execTransact:1159 <bottom of call stack> 
2021-12-08 12:13:12.932 714-755/? E/HYPER-HAL: [Request.cpp]acquire(): Request:: id : 897149, No Resource to set
2021-12-08 12:13:12.948 2728-2728/? E/pageboostd: Received HALT command code 2
2021-12-08 12:13:12.965 10984-10984/? E/android.dqagen: Not starting debugger since process cannot load the jdwp agent.
2021-12-08 12:13:13.811 1689-1689/? E/PhoneInterfaceManager: [PhoneIntfMgr] getCarrierPackageNamesForIntentAndPhone: No UICC
2021-12-08 12:13:13.812 1689-1689/? E/PhoneInterfaceManager: [PhoneIntfMgr] getCarrierPackageNamesForIntentAndPhone: No UICC
2021-12-08 12:13:13.863 11028-11028/? E/nder:appservic: Not starting debugger since process cannot load the jdwp agent.
2021-12-08 12:13:13.878 6595-9183/? E/ExternalAccountType: [C] Package was found, but that doesn't contain the CONTACTS_STRUCTURE metadata
2021-12-08 12:13:14.032 11058-11058/? E/com.motioncam: Not starting debugger since process cannot load the jdwp agent.

```

**Comment by mirsadm** [comment]
Thanks for the stack trace. Will fix this now.
